version: "3.8"

services:
  symfony-php:
    build: .
    volumes:
      - .:/var/www/html
    networks:
      - symfony-net

  symfony-nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - symfony-php
    networks:
      - symfony-net

  vue-frontend:
    build: ./frontend
    ports:
      - "8081:80"
    networks:
      - symfony-net

networks:
  symfony-net:
