nelmio_cors:
  defaults:
    allow_origin: ["*"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["http://localhost:5173"] # Vite dev server URL
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
      max_age: 3600