nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:5173","http://localhost:5174","*"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    allow_credentials: true
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["http://localhost:5173","http://localhost:5174","*"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_credentials: true
      max_age: 3600